name: Build Dockerfile

on: push

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        name: Building rdftools with Docker
        with:
          context: .
          load: true
          tags: "rdftools:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "CONAN_USER=${{ secrets.CONAN_USER }}"
            "CONAN_PW=${{ secrets.CONAN_PW }}"
      - uses: shrink/actions-docker-extract@v2
        id: extract
        name: Extracting executables from docker image
        with:
          image: "rdftools:${{ github.sha }}"
          path: rdftools/
      - uses: actions/upload-artifact@v3
        name: Uploading executables as artifacts
        with:
          name: rdftools
          path: ${{ steps.extract.outputs.destination }}/rdftools/*




