name: Build Dockerfile

on: push

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_dockerfile:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        name: Building rdftools with Docker
        with:
          context: .
          load: true
          tags: "rdftools:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Extract binaries
        run: |
          docker images
          docker create rdftools:${{ github.sha }}
      #          id=$(docker create "rdftools:${{ github.sha }}")
      #          docker export $id | tar -x --wildcards "rdftools/**"
      #          docker rm $id
      - uses: actions/upload-artifact@v3
        name: Uploading executables as artifacts
        with:
          name: rdftools
          path: rdftools/*




