name: Publish release

on:
  workflow_run:
    workflows: [ Build Dockerfile ]
    branches: [ main ]
    types: [ completed ]

concurrency:
  group: publish-release-${{ github.workflow }}-${{ github.ref }}

jobs:
  create_release:
    defaults:
      run:
        shell: bash

    name: Creates a release with static binaries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract asset version
        run: |
          VER=$(cat VERSION)
          echo "asset_version=$VER" >> $GITHUB_ENV

      - uses: dawidd6/action-download-artifact@v2
        name: Download executables artifacts built by 'Build Dockerfile' workflow
        with:
          workflow: build.yml
          name: rdftools
          path: artifacts

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/*
          tag: "v${{ env.asset_version }}"